# Generated by Django 5.2.15 on 2026-08-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_audio_message_image_alter_message_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='audio',
        ),
    ]
